from app.auth.exceptions import BaseAuthException


class VerificationError(BaseAuthException):
    pass
